---
version: '3.7'
# services:
#   web:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - "80:80"

#   nginx:
#     image: nginx:stable-alpine
#     volumes:
#       - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
#     ports:
#       - "8080:80"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
